kind: ConfigMap
apiVersion: v1
metadata:
  name: test-grafana-dashboards
  namespace: test
  labels:
    role: grafana-dashboardfiles
    grafana: test
data:
    {{- (.Files.Glob "test-dashboard.json").AsConfig | nindent 2 }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: test-grafana-dashboard-config
  namespace: test
  labels:
    role: grafana-dashboard-configfiles
    grafana: test
data:
  dashboards.yml: |-
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: test-grafana-source-config
  namespace: test
  labels:
    role: grafana-source-configfiles
    grafana: test
data:
  datasource.yml: |-
    # config file version
    apiVersion: 1
    # list of datasources that should be deleted from the database
    deleteDatasources:
      - name: prometheus
        orgId: 1
    # list of datasources to insert/update depending
    # whats available in the database
    datasources:
      # <string, required> name of the datasource. Required
    - name: prometheus
      # <string, required> datasource type. Required
      type: prometheus
      # <string, required> access mode. direct or proxy. Required
      access: proxy
      # <int> org id. will default to orgId 1 if not specified
      orgId: 1
      # <string> url 
      url: http://prometheus:9090
      # <string> database password, if used
      password:
      # <string> database user, if used
      user:
      # <string> database name, if used
      database:
      # <bool> enable/disable basic auth
      basicAuth: true
      # <string> basic auth username
      basicAuthUser: admin
      # <string> basic auth password
      basicAuthPassword: foobar
      # <bool> enable/disable with credentials headers
      withCredentials:
      # <bool> mark as default datasource. Max one per org
      isDefault:
      # <map> fields that will be converted to json and stored in json_data
      jsonData:
        graphiteVersion: "1.1"
        tlsAuth: false
        tlsAuthWithCACert: false
      # <string> json object of data that will be encrypted.
      secureJsonData:
        tlsCACert: "..."
        tlsClientCert: "..."
        tlsClientKey: "..."
      version: 1
      # <bool> allow users to edit datasources from the UI.
      editable: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-grafana
  namespace: test
  labels:
    app: test-grafana
spec:
  replicas: 1
  minReadySeconds: 0
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: test-grafana
  template:
    metadata:
      labels:
        app: test-grafana
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: requestmonitor/enabled
                operator: NotIn
                values:
                - "false"
      containers:
        - name: test-grafana
          image: grafana/grafana:6.5.2
          imagePullPolicy: Always
          volumeMounts:
            - name: grafana-dash-config
              mountPath: /etc/grafana/provisioning/dashboards
            - name: dashboard-templates
              mountPath: /var/lib/grafana/dashboards
            - name: grafana-source-config
              mountPath: /etc/grafana/provisioning/datasources
      volumes:
        - name: grafana-source-config
          configMap:
            name: test-grafana-source-config
        - name: grafana-dash-config
          configMap:
            name: test-grafana-dashboard-config
        - name: dashboard-templates
          configMap:
            name: test-grafana-dashboards
      imagePullSecrets:
        - name: docregistry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: test-grafana
  namespace: test
  labels:
    app: test-grafana
spec:
  type: NodePort
  ports:
    - port: 3000
  selector:
    app: test-grafana