apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: internal-service-monitor-sm
  labels:
    name: internal-service-monitor-sm
    prometheus: internal-service-monitor
spec: 
  selector:
    matchLabels:
      name: internal-service-monitor
  namespaceSelector:
    any: true
  endpoints:
  - port: url-rest
    targetPort: 10001